CHROMIUM: Fix MMC_FFU related build error
The following build error is seen with CONFIG_MMC=m and CONFIG_MMC_FFU=y.

ERROR: "mmc_ffu_invoke" [drivers/mmc/card/mmc_block.ko] undefined!

Even though the symbol is exported, it was not included in the build
if MMC was built as module.

BUG=chromium:583462
TEST=Build any configuration with CONFIG_MMC=m and CONFIG_MMC_FFU=y.

Change-Id: I6cc5ba08bace8072533fb84b2a9c803acdad7ef3
Fixes: 5f18c7fb5a79 ("FROMLIST: mmc: core: Support FFU for eMMC v5.0")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/329714
Reviewed-by: Olof Johansson <olofj@chromium.org>