FROMGIT: platform/x86: intel_pmc_ipc: Mark ipc_data_readb() as __maybe_unused
The function is currently not used, however it is part of the API and
might be used in the future. Adding the attribute fixes the following
warning when building with clang:

    drivers/platform/x86/intel_pmc_ipc.c:189:18: error: unused function
        'ipc_data_readb' [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build for pyro with clang

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: Andy Shevchenko <andriy.shevchenko@linux.intel.com>
(cherry picked from git.infradead.org linux-platform-drivers-x86 testing
commit 6bee1af9dcaa05c2b9289ec26ed121039dfea251)

Change-Id: I3357c4d0892472bc48ea783a131770cff36df297
Reviewed-on: https://chromium-review.googlesource.com/517242
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>