fs/crypto/hooks.c: fix build with gcc-4.4.4
gcc-4.4.4 has issues with anon union initializers.  Work around this.

fs/crypto/hooks.c: In function '__fscrypt_encrypt_symlink':
fs/crypto/hooks.c:161: error: unknown field 'len' specified in initializer
fs/crypto/hooks.c:161: warning: excess elements in struct initializer
fs/crypto/hooks.c:161: warning: (near initialization for 'iname')

Fixes: 76e81d6d50 ("fscrypt: new helper functions for ->symlink()")
Cc: Eric Biggers <ebiggers@google.com>
Cc: Theodore Ts'o <tytso@mit.edu>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>