CHROMIUM: pinctrl: tegra-xusb: Add dependency on USB_COMMON!=m
The following error is seen if USB_COMMON is built as module and
PINCTRL_TEGRA_XUSB is built into the kernel.

drivers/built-in.o: In function `tegra_xusb_setup_usb':
:(.text+0x3afd8): undefined reference to `of_usb_get_dr_mode'

of_usb_get_dr_mode() is declared as dummy id OF is not configured.
Otherwise it is available only if USB_COMMON is built into the kernel.
PINCTRL_TEGRA_XUSB therefore depends on USB_COMMON!=m.

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Change-Id: I49536a121f1631a80e60b7d6c0155e1c478346a5
Fixes: 260dc97ffa48e ("CHROMIUM: pinctrl: tegra-xusb: Support dual-role PHY")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328976
Commit-Ready: Olof Johansson <olofj@chromium.org>
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>