UPSTREAM: include/linux/kmemleak.h: needs slab.h
include/linux/kmemleak.h: In function 'kmemleak_alloc_recursive':
include/linux/kmemleak.h:43: error: 'SLAB_NOLEAKTRACE' undeclared (first use in this function)

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Cc: Joonsoo Kim <iamjoonsoo.kim@lge.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Linus Torvalds <torvalds@linux-foundation.org>
(cherry picked from commit 66f2ca7e3f59312888131546176b42d6e248558a)
Change-Id: I66524e9d8e34e9efb2f00f5db321fe9f4757fc16
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328304
Reviewed-by: Olof Johansson <olofj@chromium.org>