CHROMIUM: ASoC: wm9713: Replace w->codec with snd_soc_dapm_to_codec(w->dapm)
Commit 33dac9ed64a6 ("UPSTREAM: ASoC: Remove codec field from
snd_soc_dapm_widget") removed the codec field from struct snd_soc_dapm_widget
but missed its use in the wm9713 driver. This causes the following build error.

sound/soc/codecs/wm9713.c: In function 'mixer_event':
sound/soc/codecs/wm9713.c:250:17: error:
	'struct snd_soc_dapm_widget' has no member named 'codec'

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Change-Id: I5468d40844cc5e918801562792e68e7597408074
Fixes: 33dac9ed64a6 ("UPSTREAM: ASoC: Remove codec field from snd_soc_dapm_widget")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328973
Reviewed-by: Olof Johansson <olofj@chromium.org>