CHROMIUM: platform: chrome: Fix build error
allmodconfig builds fail with

ERROR: "cros_ec_lpc_io_bytes_mec" [drivers/platform/chrome/cros_ec_lpcs.ko] undefined!
ERROR: "cros_ec_lpc_mec_destroy" [drivers/platform/chrome/cros_ec_lpcs.ko] undefined!
ERROR: "cros_ec_lpc_mec_init" [drivers/platform/chrome/cros_ec_lpcs.ko] undefined!

The MEC code is built into the kernel if enabled, which is wrong. Adjust Makefile
to add it to cros_ec_lpcs.

Signed-off-by: Guenter Roeck <linux@roeck-us.net>

Conflicts:
	drivers/platform/chrome/Makefile

[rebase49(groeck): Context conflicts]
Signed-off-by: Guenter Roeck <groeck@chromium.org>