ovl: fix link error without POSIX ACL
The latest fix for ACL on overlayfs introduced a link error:

fs/built-in.o: In function `ovl_posix_acl_xattr_set':
file.c:(.text+0x6b320): undefined reference to `posix_acl_from_xattr'

posix_acl_from_xattr doesn't have a 'static inline' implementation when
CONFIG_FS_POSIX_ACL is disabled, and I could not come up with an obvious
way to do it.

This instead avoids the link error by defining two sets of ACL operations
and letting the compiler drop one of the two at compile time depending
on CONFIG_FS_POSIX_ACL. This avoids all references to the ACL code,
also leading to smaller code.

Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Fixes: f9bc66ad93b8 ("ovl: fix POSIX ACL setting")
Signed-off-by: Miklos Szeredi <mszeredi@redhat.com>