CHROMIUM: dmaengine: tegra-adma: Use div_u64_rem() for 64-bit divide
Building tegra-adma on a 32 bit target fails with the following linker
error.

drivers/built-in.o: In function `tegra_adma_tx_status':
:(.text+0x124050): undefined reference to `__aeabi_uldivmod'
:(.text+0x124144): undefined reference to `__aeabi_uldivmod'

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Change-Id: I0db412c89b326090a6f3b2824c95649ecc97f3cd
Fixes: 3fbfadbe5f66a ("CHROMIUM: add ADMA driver for NVidia T210 SoC:)
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/329182
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>