mm-page_alloc-re-enable-softirq-use-of-per-cpu-page-allocator-checkpatch-fixes
ERROR: Please use git commit description style 'commit <12+ chars of sha1> ("<title line>")' - ie: 'commit 0123456789ab ("commit description")'
#19:
patch, the result wiill be to revert 374ad05ab64d and try again at a later

ERROR: space prohibited before that close parenthesis ')'
#120: FILE: mm/page_alloc.c:2722:
+	if (likely(order == 0) && !(in_irq() || irqs_disabled()) ) {

total: 2 errors, 0 warnings, 75 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-page_alloc-re-enable-softirq-use-of-per-cpu-page-allocator.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Jesper Dangaard Brouer <brouer@redhat.com>
Cc: Mel Gorman <mgorman@techsingularity.net>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>