CHROMIUM: staging: drm/imx: Fix parameters to drm_encoder_init
Commit 10805f4d5b99 ("BACKPORT: drm: Pass 'name' to drm_encoder_init()")
added an additional parameter to drm_encoder_init, but missed several
calls in imx-drm code. This causes build errors when trying to build
arm:allmodconfig or arm:imx_v6_v7_defconfig.

drivers/staging/imx-drm/imx-ldb.c: In function 'imx_ldb_register':
drivers/staging/imx-drm/imx-ldb.c:373:2: error:
	too few arguments to function 'drm_encoder_init'

drivers/staging/imx-drm/imx-hdmi.c: In function 'imx_hdmi_register':
drivers/staging/imx-drm/imx-hdmi.c:1553:2: error:
	too few arguments to function 'drm_encoder_init'

drivers/staging/imx-drm/imx-tve.c: In function 'imx_tve_register':
drivers/staging/imx-drm/imx-tve.c:509:2: error:
	too few arguments to function 'drm_encoder_init'

BUG=chromium:583462
TEST=None (build)

Change-Id: Ifd17babf207dcaea9548e3a463753e98950adc0c
Fixes: 10805f4d5b99 ("BACKPORT: drm: Pass 'name' to drm_encoder_init()")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328720
Reviewed-by: Olof Johansson <olofj@chromium.org>