FROMGIT: x86/ioapic: Remove unused IO_APIC_irq_trigger() function
The function isn't used since commit:

  5ad274d41c1b ("x86/irq: Remove unused old IOAPIC irqdomain interfaces")

Removing it fixes the following warning when building with clang:

  arch/x86/kernel/apic/io_apic.c:1219:19: error: unused function
      'IO_APIC_irq_trigger' [-Werror,-Wunused-function]

BUG=chromium:702741
TEST=build for pyro with clang

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Cc: Andrew Morton <akpm@linux-foundation.org>
Cc: Douglas Anderson <dianders@chromium.org>
Cc: Linus Torvalds <torvalds@linux-foundation.org>
Cc: Peter Zijlstra <peterz@infradead.org>
Cc: Thomas Gleixner <tglx@linutronix.de>
Link: http://lkml.kernel.org/r/20170522232035.187985-1-mka@chromium.org
Signed-off-by: Ingo Molnar <mingo@kernel.org>
(cherry picked from git.kernel.org tip irq/tipcore commit
b9de5068b2d7c22de1bb89d62a7119a6b8dff88f)

Change-Id: I54751306bc87275b328f689cdcbf64765283e6c6
Reviewed-on: https://chromium-review.googlesource.com/512764
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>