CHROMIUM: Fix dependencies for TEGRA_THERM_EST and TEGRA_CPU_EDP
If TEGRA_THERM_EST is configured, and THERMAL is configured as module
or not at all, the build fails with

drivers/built-in.o: In function `tegra_cpu_edp_probe':
:(.text+0x151500): undefined reference to `thermal_zone_get_zone_by_node'

Fix the problem by providing a dummy function if THERMAL is not configured,
and by restricting TEGRA_CPU_EDP and TEGRA_THERM_EST to be buildable only
if THERMAL is configured to be built into the kernel.

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Change-Id: Ie1eee5caae2490498162f4db3d644d732233ceb4
Fixes: e67f0c4a0cca ("CHROMIUM: thermal: use device node to get thermal zone")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328975
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>