CHROMIUM: google memconsole: Replace ioremap_cache() with memremap()
ioremap_cache() is deprecated and not or no longer supported
on all architectures. This can result in the following build error
(seen on mips).

drivers/firmware/google/memconsole.c: In function 'memconsole_coreboot_init':
drivers/firmware/google/memconsole.c:52:2: error:
	implicit declaration of function 'ioremap_cache'

BUG=None
TEST=Load on a system supporting memconsole and ensure that it works.

Signed-off-by: Guenter Roeck <groeck@chromium.org>