s390/decompressor: add fortify_panic as x86 has.
Fix following error:

  LD      arch/s390/boot/compressed/vmlinux
drivers/s390/char/sclp_early_core.o: In function `memcpy':
../include/linux/string.h:340: undefined reference to `fortify_panic'
make[4]: *** [../arch/s390/boot/compressed/Makefile:29: arch/s390/boot/compressed/vmlinux] Error 1

Fixes: 79962038dffa ("s390: add support for FORTIFY_SOURCE")
Signed-off-by: Michal Suchanek <msuchanek@suse.de>
Signed-off-by: Martin Schwidefsky <schwidefsky@de.ibm.com>