CHROMIUM: Bluetooth: Add missing 6lowpan helper functions
6lowpan fails to build on arm with the following errors.

net/bluetooth/6lowpan.c: In function 'recv_pkt':
net/bluetooth/6lowpan.c:328:2: error:
	implicit declaration of function 'lowpan_is_ipv6'

net/bluetooth/6lowpan.c:352:2: error:
	implicit declaration of function 'lowpan_is_iphc'

Pull the missing inline functions from upstream commit 72a5e6bb5120d
("ieee820154: 6lowpan: dispatch evaluation rework").

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Change-Id: I4fa42623d3fd37153e10b6948b869382cbe852d4
Fixes: 585993a62ad8 ("CHROMIUM: Bluetooth: update stack to bluetooth-next")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328972
Reviewed-by: Olof Johansson <olofj@chromium.org>
Reviewed-by: Sameer Nanda <snanda@chromium.org>