mmc: s3cmci: fix broken conditional expression
The DT support introduced a typo that gcc detects when -Wempty-body
is enabled:

drivers/mmc/host/s3cmci.c: In function 's3cmci_probe_pdata':
drivers/mmc/host/s3cmci.c:1543:29: error: suggest braces around empty body in an 'if' statement [-Werror=empty-body]
  if (pdata->wprotect_invert);

Clearly the ';' was not intended here, so remove it.

Fixes: 4b13f3b290d1 ("mmc: host: s3cmci: allow probing from device tree")
Signed-off-by: Arnd Bergmann <arnd@arndb.de>
Signed-off-by: Ulf Hansson <ulf.hansson@linaro.org>