CHROMIUM: Revert "ANDROID: net: wireless: bcmdhd: Enable SAR control for bcm4358"
This reverts commit a59de02cf775a9bb919c5efcd8d453e84ba6afdb.

Attempts to build the bcmdhd driver with BCM4358 enabled result
in the following build error.

drivers/built-in.o: In function `dhd_detach':
(.text+0x1b22f31): undefined reference to `unregister_notifier_by_sar'
drivers/built-in.o: In function `dhd_attach':
(.text+0x1b23a6c): undefined reference to `register_notifier_by_sar'

Those functions are not available in the chromeos-3.18 kernel,
nor in android-3.18, and we can not enable SAR without it.

BUG=chromium:583462
TEST=Build x86_64:allyesconfig

Change-Id: I878f438536d9787b057ae8d87d7fba27aa0662ce
Fixes: a59de02cf775 ("ANDROID: net: wireless: bcmdhd: Enable SAR control for bcm4358")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/333670
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-by: Dmitry Shmidt <dimitrysh@google.com>