CHROMIUM: drm/armada: Fix parameters to drm_encoder_init
Commit 10805f4d5b99 ("BACKPORT: drm: Pass 'name' to drm_encoder_init()")
added an additional parameter to drm_encoder_init, but missed a call
in armada code, presumably because it is not upstream. This causes a build
error when trying to build arm:allmodconfig.

drivers/gpu/drm/armada/armada_slave.c:92:8: error:
	too few arguments to function 'drm_encoder_init'

BUG=chromium:583462
TEST=None (build)

Change-Id: I106ec3c0bb2f04f6935b3ac1c0f33ffb5c942b45
Fixes: 10805f4d5b99 ("BACKPORT: drm: Pass 'name' to drm_encoder_init()")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328721
Reviewed-by: Olof Johansson <olofj@chromium.org>