CHROMIUM: drm/tilcdc: Fix parameters to drm_encoder_init
Commit 10805f4d5b99 ("BACKPORT: drm: Pass 'name' to drm_encoder_init()")
added an additional parameter to drm_encoder_init, but missed a call
in tilcdc code. This causes build errors when trying to build
arm:allmodconfig.

drivers/gpu/drm/tilcdc/tilcdc_slave.c: In function 'slave_encoder_create':
drivers/gpu/drm/tilcdc/tilcdc_slave.c:136:8: error:
	too few arguments to function 'drm_encoder_init'

BUG=chromium:583462
TEST=None (build)

Change-Id: Ibe090af86c817455f5b9f7c05e331a06629292a8
Fixes: 10805f4d5b99 ("BACKPORT: drm: Pass 'name' to drm_encoder_init()")
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/328724
Reviewed-by: Olof Johansson <olofj@chromium.org>