UPSTREAM: x86: mm: Move PAT only functions to mm/pat.c
Commit e00c8cc93c1a "x86: Use new cache mode type in memtype related
functions" broke the ARCH=um build.

 arch/x86/include/asm/cacheflush.h:67:36: error: return type is an incomplete type
 static inline enum page_cache_mode get_page_memtype(struct page *pg)

The reason is simple. get_page_memtype() and set_page_memtype()
require enum page_cache_mode now, which is defined in
asm/pgtable_types.h. UM does not include that file for obvious reasons.

The simple solution is to move that functions to arch/x86/mm/pat.c
where the only callsites of this are located. They should have been
there in the first place.

Fixes: e00c8cc93c1a "x86: Use new cache mode type in memtype related functions"
Reported-by: Fengguang Wu <fengguang.wu@intel.com>
Signed-off-by: Thomas Gleixner <tglx@linutronix.de>
Cc: Juergen Gross <jgross@suse.com>
Cc: Richarad Weinberger <richard@nod.at>
(cherry picked from commit 0dbcae884779fdf7e2239a97ac7488877f0693d9)
Signed-off-by: Andrew-CT Chen <andrew-ct.chen@mediatek.com>

BUG=chrome-os-partner:49541
TEST=build oak, strago, smaug and allnoconfig, and boot oak-rev3

Change-Id: Ia6b3ae15378f2cf203391a3673fc2709be3a6a4a
Reviewed-on: https://chromium-review.googlesource.com/330227
Commit-Ready: Daniel Kurtz <djkurtz@chromium.org>
Tested-by: Andrew-CT Chen <andrew-ct.chen@mediatek.com>
Reviewed-by: Andrew Bresticker <abrestic@chromium.org>