mm-thp-use-down_read_trylock-in-khugepaged-to-avoid-long-block-fix-checkpatch-fixes
ERROR: code indent should use tabs where possible
#26: FILE: mm/khugepaged.c:1677:
+ ^I * Don't wait for semaphore (to avoid long wait times).  Just move to$

WARNING: please, no space before tabs
#26: FILE: mm/khugepaged.c:1677:
+ ^I * Don't wait for semaphore (to avoid long wait times).  Just move to$

total: 1 errors, 1 warnings, 10 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

NOTE: Whitespace errors detected.
      You may wish to use scripts/cleanpatch or scripts/cleanfile

./patches/mm-thp-use-down_read_trylock-in-khugepaged-to-avoid-long-block-fix.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Yang Shi <yang.s@alibaba-inc.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>