net: socket ioctl to reset connections matching local address
Introduce a new socket ioctl, SIOCKILLADDR, that nukes all sockets
bound to the same local address. This is useful in situations with
dynamic IPs, to kill stuck connections.

Signed-off-by: Brian Swetland <swetland@google.com>

net: fix tcp_v4_nuke_addr

Signed-off-by: Dima Zavin <dima@android.com>

net: ipv4: Fix a spinlock recursion bug in tcp_v4_nuke.

We can't hold the lock while calling to tcp_done(), so we drop
it before calling. We then have to start at the top of the chain again.

Signed-off-by: Dima Zavin <dima@android.com>

net: ipv4: Fix race in tcp_v4_nuke_addr().

To fix a recursive deadlock in 2.6.29, we stopped holding the hash table lock
across tcp_done() calls. This fixed the deadlock, but introduced a race where
the socket could die or change state.

Fix: Before unlocking the hash table, we grab a reference to the socket. We
can then unlock the hash table without risk of the socket going away. We then
lock the socket, which is safe because it is pinned. We can then call
tcp_done() without recursive deadlock and without race. Upon return, we unlock
the socket and then unpin it, killing it.

Old-Change-Id: Idcdae072b48238b01bdbc8823b60310f1976e045
Signed-off-by: Robert Love <rlove@google.com>
Acked-by: Dima Zavin <dima@android.com>

ipv4: disable bottom halves around call to tcp_done().

Signed-off-by: Robert Love <rlove@google.com>
Signed-off-by: Colin Cross <ccross@android.com>

ipv4: Move sk_error_report inside bh_lock_sock in tcp_v4_nuke_addr

When sk_error_report is called, it wakes up the user-space thread, which then
calls tcp_close.  When the tcp_close is interrupted by the tcp_v4_nuke_addr
ioctl thread running tcp_done, it leaks 392 bytes and triggers a WARN_ON.

This patch moves the call to sk_error_report inside the bh_lock_sock, which
matches the locking used in tcp_v4_err.

Old-Change-Id: I34614f7b393182f65091b7a5f19ffa7776c2c575
Signed-off-by: Colin Cross <ccross@android.com>
Reviewed-on: https://chromium-review.googlesource.com/423136
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

net: fix iterating over hashtable in tcp_nuke_addr()

The actual size of the tcp hashinfo table is tcp_hashinfo.ehash_mask + 1
so we need to adjust the loop accordingly to get the sockets hashed into
the last bucket.

Old-Change-Id: I796b3c7b4a1a7fa35fba9e5192a4a403eb6e17de
Signed-off-by: Dmitry Torokhov <dtor@google.com>
Reviewed-on: https://chromium-review.googlesource.com/423137
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

net: fix crash in tcp_nuke_addr()

When iterating through sockets we need to skip sockets in TIME_WAIT
state as they use lightweight structure inet_timewait_sock that does not
have sk_lock member, and if we try to lock them we'll crash thusly:

[   89.376383] BUG: spinlock lockup suspected on CPU#0, netd/431
[   89.382139]  lock: 0xffffffc039d05070, .magic: 66d30606, .owner: /-1682098992, .owner_cpu: 0
[   89.390598] CPU: 0 PID: 431 Comm: netd Tainted: G     U  W 3.18.0 #5
[   89.397389] Hardware name: Google Tegra210 Smaug Rev 1+ (DT)
[   89.403049] Call trace:
[   89.405501] [<ffffffc0002072b4>] dump_backtrace+0x0/0x10c
[   89.410918] [<ffffffc0002073d0>] show_stack+0x10/0x1c
[   89.415971] [<ffffffc000a88608>] dump_stack+0x74/0x94
[   89.421018] [<ffffffc000257e8c>] spin_dump+0x78/0x88
[   89.425984] [<ffffffc0002580d8>] do_raw_spin_lock+0xfc/0x158
[   89.431666] [<ffffffc000a90090>] _raw_spin_lock+0x34/0x44
[   89.437059] [<ffffffc0009509a8>] tcp_nuke_addr+0x1fc/0x29c
[   89.442548] [<ffffffc0009735f4>] devinet_ioctl+0x288/0x680
[   89.448053] [<ffffffc000975004>] inet_ioctl+0xc4/0xf4
[   89.453103] [<ffffffc0008baedc>] sock_do_ioctl+0x2c/0x5c
[   89.458408] [<ffffffc0008bbb54>] sock_ioctl+0x210/0x230
[   89.463633] [<ffffffc000317088>] do_vfs_ioctl+0x4ac/0x590
[   89.469049] [<ffffffc0003171c8>] SyS_ioctl+0x5c/0x88

(or with NULL pointer dereference if lockdep is still working).

Old-Change-Id: I07c70d9a60b125b1070ff05c4eec27daee1a3e90
Signed-off-by: Dmitry Torokhov <dtor@google.com>
Reviewed-on: https://chromium-review.googlesource.com/423138
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

tcp: Fix IPV6 module build errors

If CONFIG_IPV6=m is selected, we are getting following build errors.

net/built-in.o: In function `tcp_is_local6':
net/ipv4/tcp.c:3261: undefined reference to `rt6_lookup'

Making the code conditional upon only CONFIG_IPV6=y fixes this issue.

Also export tcp_nuke_addr to build IPv6 modules. Otherwise
we run into following build error:

  CC [M]  lib/zlib_deflate/deftree.o
  CC [M]  lib/zlib_deflate/deflate_syms.o
  LD [M]  lib/zlib_deflate/zlib_deflate.o
  Building modules, stage 2.
  MODPOST 46 modules
ERROR: "tcp_nuke_addr" [net/ipv6/ipv6.ko] undefined!
make[2]: *** [__modpost] Error 1

Old-Change-Id: Ied391ef57198175d5c0cd06d5547cab061ffab29
Signed-off-by: Tushar Behera <tushar.behera@linaro.org>
CC: John Stultz <john.stultz@linaro.org>
Signed-off-by: John Stultz <john.stultz@linaro.org>
Signed-off-by: Amit Pundir <amit.pundir@linaro.org>
Reviewed-on: https://chromium-review.googlesource.com/423139
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

CHROMIUM: net: tcp: Only perform IPv6 functions is IPv6 is built-in

Build error with IPv6 built as module:

net/built-in.o: In function `tcp_is_local6':
net/ipv4/tcp.c:3156: undefined reference to `rt6_lookup'

Alternative would be to define IPV6 as boolean, but that causes trouble
elsewhere.

Fixes: c7c3ec4903d3 ("net: socket ioctl to reset connections matching local address")
BUG=chromium:583462
TEST=None (build)

Original-Change-Id: I98ef6d237b79355004ffdc223bce2e23fe368437
Old-Change-Id: I4f0145467e5e565cf4c3c8e24e79087a956eccc5
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/344368
Commit-Ready: Kevin Cernekee <cernekee@chromium.org>
Tested-by: Kevin Cernekee <cernekee@chromium.org>
Reviewed-by: Guenter Roeck <groeck@google.com>
Reviewed-on: https://chromium-review.googlesource.com/423140
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

CHROMIUM: net: tcp: Export tcp_nuke_addr

Otherwise compilation may fail if IPv6 is built as module.

ERROR: "tcp_nuke_addr" [net/ipv6/ipv6.ko] undefined!

Fixes: c7c3ec4903d3 ("net: socket ioctl to reset connections matching local address")
BUG=chromium:583462
TEST=None (build)

Original-Change-Id: Ib18a74aa251cfd3674aa152442a52552e59123b3
Old-Change-Id: I51d2b29ea7b3206ebbce969a121d11a2e7947cf2
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/344369
Commit-Ready: Kevin Cernekee <cernekee@chromium.org>
Tested-by: Kevin Cernekee <cernekee@chromium.org>
Reviewed-by: Guenter Roeck <groeck@google.com>
Reviewed-on: https://chromium-review.googlesource.com/423141
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

CHROMIUM: Add more sanity checks to tcp_nuke_addr()

Currently this function will nuke connections in other namespaces, and
it will nuke connections even if the socket type does not match.
This allows guest OSes running in containers to crea unwanted
interference with the host OS.

BUG=b:29515384
TEST=`android-sh -c "ip -6 addr add fc00::1/128 dev arc0; ip -6 addr del fc00::1/128 dev arc0"`

Old-Change-Id: Id1431ac457b104252b60e8d171e01724b52b5a91
Signed-off-by: Kevin Cernekee <cernekee@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/354087
Reviewed-by: Dmitry Torokhov <dtor@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/423142
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>

CHROMIUM: Refactor tcp_nuke_addr() matching logic

This code needs to meet the following requirements:

 - Match both "native" IPv4 sockets and IPv6-mapped-IPv4 sockets
   (currently the latter sockets are ignored, and Android uses them
   extensively).

 - Don't nuke connections on loopback interfaces.  Currently this logic
   is broken, because tcp_is_local() always returns true.  This happens
   because it uses the routing code, which always sends packets destined
   for local interfaces through lo:

        # ip route get 100.107.2.11
        local 100.107.2.11 via ??? ??? dev lo  src 100.107.2.11

   Instead, the code will explicly check whether the local address is in
   the loopback range.

 - As a quirk of how ADB and CTS work under Chrome OS, the ADB port
   (5555/tcp) must be excluded from nuking to avoid failing tests.
   An explicit check is added for this condition, per b/31635190.

BUG=b:30261109
TEST=`nuketest 0.0.0.0` and see whether it resets IPv4, mapped IPv4, or
     IPv6 connections
TEST=`nuketest 0.0.0.1`
TEST=`nuketest ::`
TEST=`nuketest ::1`

Old-Change-Id: I47be2a35a358d9f4e5e79623b639a84c84bb522d
Signed-off-by: Kevin Cernekee <cernekee@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/407923
Reviewed-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-on: https://chromium-review.googlesource.com/423143
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>

Conflicts:
	net/ipv4/tcp.c

[rebase49(groeck): Resolved conflicts]
Signed-off-by: Guenter Roeck <groeck@chromium.org>

net: Add SIOCKILLADDR ioctl in the compatibility list

SIOCKILLADDR is not present as an option in the compatibility list of
supported ioctls. This means that a 32-bit binary gets a not
supported error when it calls this ioctl on a 64-bit kernel. This
change adds the SIOCKILLADDR to the compatibility list.

BUG=b:32705013
TEST=Tested with Youtube Kids app as mentioned in the bug

Change-Id: Ifad88e17b313f260cfdadf2b3a67601dce8928bc
Reviewed-on: https://chromium-review.googlesource.com/423144
Commit-Ready: Abhishek Bhardwaj <abhishekbh@google.com>
Tested-by: Abhishek Bhardwaj <abhishekbh@google.com>
Reviewed-by: Kevin Cernekee <cernekee@chromium.org>

[rebase49(groeck): Merged all 'nuke' commits into one]
Signed-off-by: Guenter Roeck <groeck@chromium.org>