include/linux/mtd/rawnand.h: fix build with gcc-4.4.4
gcc-4.4.4 has issues with anon union initializers.  Work aound this.

drivers/mtd/nand/marvell_nand.c:1936: warning: missing braces around initializer
drivers/mtd/nand/marvell_nand.c:1936: warning: (near initialization for '(anonymous)[1].<anonymous>')
drivers/mtd/nand/marvell_nand.c:1936: error: unknown field 'data' specified in initializer
drivers/mtd/nand/marvell_nand.c:1936: error: unknown field 'addr' specified in initializer
drivers/mtd/nand/marvell_nand.c:1936: warning: missing braces around initializer
drivers/mtd/nand/marvell_nand.c:1936: warning: (near initialization for '(anonymous)[1].<anonymous>')
drivers/mtd/nand/marvell_nand.c:1936: error: unknown field 'data' specified in initializer
drivers/mtd/nand/marvell_nand.c:1936: error: unknown field 'addr' specified in i

Fixes: 02f26ecf8c77275 ("mtd: nand: add reworked Marvell NAND controller driver")
Cc: Miquel Raynal <miquel.raynal@free-electrons.com>
Cc: Sean Nyekjaer <sean.nyekjaer@prevas.dk>
Cc: Willy Tarreau <w@1wt.eu>
Cc: Boris Brezillon <boris.brezillon@free-electrons.com>
Cc: Richard Weinberger <richard@nod.at>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>
Signed-off-by: Stephen Rothwell <sfr@canb.auug.org.au>