mm-hugetlb-report-ehwpoison-not-efault-when-foll_hwpoison-is-specified-checkpatch-fixes
ERROR: open brace '{' following function declarations go on the next line
#47: FILE: include/linux/mm.h:2330:
+static inline int vm_fault_to_errno(int vm_fault, int foll_flags) {

WARNING: Missing a blank line after declarations
#74: FILE: mm/gup.c:485:
+		int err = vm_fault_to_errno(ret, *flags);
+		if (err)

total: 1 errors, 1 warnings, 41 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/mm-hugetlb-report-ehwpoison-not-efault-when-foll_hwpoison-is-specified.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: James Morse <james.morse@arm.com>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>