FROMGIT: net1080: Remove unused function nc_dump_ttl()
The function is not used, removing it fixes the following warning when
building with clang:

drivers/net/usb/net1080.c:271:20: error: unused function
    'nc_dump_ttl' [-Werror,-Wunused-function]

Also remove the definition of TTL_THIS, which is only used in
nc_dump_ttl()

BUG=chromium:702741
TEST=build with clang for pyro

Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Signed-off-by: David S. Miller <davem@davemloft.net>
(cherry picked from git.kernel.org davem/net-next master
commit ce064e68a7e1ae525cd525fac3a6901591ddae3c)

Change-Id: I953cf3adb23641050084796c8b1d8f00ad14eddd
Reviewed-on: https://chromium-review.googlesource.com/508445
Commit-Ready: Matthias Kaehlcke <mka@chromium.org>
Tested-by: Matthias Kaehlcke <mka@chromium.org>
Reviewed-by: Douglas Anderson <dianders@chromium.org>