CHROMIUM: drm/panel: lpm102a188a: Do not use unset variable
drivers/gpu/drm/panel/panel-jdi-lpm102a188a.c:
	In function 'panel_jdi_setup_primary':
drivers/gpu/drm/panel/panel-jdi-lpm102a188a.c:773:3: error:
	'ret' may be used uninitialized in this function

There is no known error code, so don't try to display it.

Fixes: 2e14d1dfada53 ("CHROMIUM: drm/panel: Add jdi lpm102a188a panel driver")
BUG=chromium:583462
TEST=None (build)

Change-Id: I07548624ee74f3159cc330beafc2a6be1f7c5d0d
Signed-off-by: Guenter Roeck <linux@roeck-us.net>
Signed-off-by: Olof Johansson <olofj@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/325377
Reviewed-by: David Riley <davidriley@chromium.org>