CHROMIUM: iwl7000: backports: port S16_* backport frmo master
We merged a backport change in master but can't cherry-pick
it in Core18. Port the fix manually to Core18.

This fixes:
drivers/net/wireless/intel/iwlwifi/mvm/tt.c:521:39: error: 'S16_MIN' undeclared (first use in this function)
   if (mvm->tz_device.temp_trips[i] != S16_MIN) {

Signed-off-by: Emmanuel Grumbach <emmanuel.grumbach@intel.com>
iwl7000-tree: 13e4fe028cfec7b5b8b47bdbad0127a12abffd7f