CHROMIUM: thermal: tegra: Add missing include file
Building arm:allmodconfig fails with

drivers/thermal/tegra/tegra_soctherm.c: In function 'temp_log_show':
drivers/thermal/tegra/tegra_soctherm.c:2329:2: error:
	implicit declaration of function 'cpu_clock'

cpu_clock() is declared in linux/sched.h which needs to be included.

BUG=chromium:583462
TEST=None (build arm:allmodconfig)

Fixes: ebf52ec2ef24b ("CHROMIUM: thermal: tegra-soctherm: export soctherm hw info in sysfs")
Signed-off-by: Guenter Roeck <groeck@chromium.org>

Change-Id: I309c5576f2bcdf347e93f0c84d0ab2dce14610cb
Reviewed-on: https://chromium-review.googlesource.com/328971
Commit-Ready: Guenter Roeck <groeck@chromium.org>
Tested-by: Guenter Roeck <groeck@chromium.org>
Reviewed-by: Olof Johansson <olofj@chromium.org>