UPSTREAM: selinux: Remove redundant check for unknown labeling behavior
The check is already performed in ocontext_read() when the policy is
loaded. Removing the array also fixes the following warning when
building with clang:

security/selinux/hooks.c:338:20: error: variable 'labeling_behaviors'
    is not needed and will not be emitted
    [-Werror,-Wunneeded-internal-declaration]

BUG=chromium:702741
TEST=build for pyro with clang

Change-Id: I54b9b5bed6f75a04f32f238b58c55a876776d5ab
Signed-off-by: Matthias Kaehlcke <mka@chromium.org>
Acked-by: Stephen Smalley <sds@tycho.nsa.gov>
Signed-off-by: Paul Moore <paul@paul-moore.com>
Signed-off-by: Guenter Roeck <groeck@chromium.org>
(cherry picked from commit 270e8573145a)