sysctl-handle-error-writing-uint_max-to-u32-fields-checkpatch-fixes
WARNING: please, no spaces at the start of a line
#101: FILE: kernel/sysctl.c:2297:
+    return do_proc_dointvec(table,write,buffer,lenp,ppos,$

ERROR: space required after that ',' (ctx:VxV)
#101: FILE: kernel/sysctl.c:2297:
+    return do_proc_dointvec(table,write,buffer,lenp,ppos,
                                  ^

ERROR: space required after that ',' (ctx:VxV)
#101: FILE: kernel/sysctl.c:2297:
+    return do_proc_dointvec(table,write,buffer,lenp,ppos,
                                        ^

ERROR: space required after that ',' (ctx:VxV)
#101: FILE: kernel/sysctl.c:2297:
+    return do_proc_dointvec(table,write,buffer,lenp,ppos,
                                               ^

ERROR: space required after that ',' (ctx:VxV)
#101: FILE: kernel/sysctl.c:2297:
+    return do_proc_dointvec(table,write,buffer,lenp,ppos,
                                                    ^

WARNING: ENOSYS means 'invalid syscall nr' and nothing else
#115: FILE: kernel/sysctl.c:2899:
+	return -ENOSYS;

total: 4 errors, 2 warnings, 74 lines checked

NOTE: For some of the reported defects, checkpatch may be able to
      mechanically convert to the typical style using --fix or --fix-inplace.

./patches/sysctl-handle-error-writing-uint_max-to-u32-fields.patch has style problems, please review.

NOTE: If any of the errors are false positives, please report
      them to the maintainer, see CHECKPATCH in MAINTAINERS.

Please run checkpatch prior to sending patches

Cc: Subash Abhinov Kasiviswanathan <subashab@codeaurora.org>
Signed-off-by: Andrew Morton <akpm@linux-foundation.org>