CHROMIUM: md: verity-chromeos: Use module_param_string()
The verity-chromeos currently accesses and parses saved_command_line
directly to read the "kern_guid=" command line parameter. Since
saved_command_line is not exported, this can result in the following
build error if dm-verity-chromeos is built as module.

ERROR: "saved_command_line" [drivers/md/dm-verity-chromeos.ko] undefined!

Use module_param_string() instead.

BUG=chromium:583462
TEST=Build and test cyan image

Change-Id: Ia98194c3d4e164122c751f578a01a6306fdbbeb3
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/332226
Reviewed-by: Olof Johansson <olofj@chromium.org>