CHROMIUM: mfd: cros_ec: Export cros_ec_get_host_event()
cros_ec_get_host_event() is called from drivers which can be built as
module. Doing so results in the following build errors.

ERROR: "cros_ec_get_host_event" [drivers/power/cros_usbpd-charger.ko] undefined!
ERROR: "cros_ec_get_host_event" [drivers/extcon/extcon-cros_ec.ko] undefined!

BUG=chromium:583462
TEST=Build x86_64:allmodconfig

Change-Id: Ieebc9901ce22b5f1be1f81b4fc6bb3467dcb26c4
Signed-off-by: Guenter Roeck <groeck@chromium.org>
Reviewed-on: https://chromium-review.googlesource.com/331981
Reviewed-by: Olof Johansson <olofj@chromium.org>